### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by shiningliang** [maxuewei2/JLUMasterThesisLaTeX#1]
你好，请问我在本地编译的，默认还是思源宋体吗？我想用标准的宋体，需要怎么改一下

**Comment by maxuewei2** [comment]
可以参考[example_files](https://github.com/maxuewei2/JLUThesis2020/tree/master/example_files)里的假粗体方案，那个是用的Adobe Song Std，应该是比较接近微软宋体的感觉的。

使用假粗体需在 documentclass 中设置 AutoFakeBold， 在 jluthesis2020 中设置 manualSpine，并需重置 CJKmainfont。

**Comment by shiningliang** [comment]
感谢回复，后来我看了下北大的模板，参考他们改了sty，在本地编译，目前字体配置是这样的
```
\setCJKmainfont[AutoFakeBold=true]{SimSun}   % 中文缺省字体: 宋体
\setCJKsansfont{KaiTi}  % 中文无衬线字体：楷体
\setCJKmonofont{SimSun}   % 中文数学字体：宋体
\setmainfont{Times New Roman}    % 英文缺省字体：替代 Times New Roman
\setsansfont{Arial}      % 英文无衬线字体: 替代 Arial
\setmonofont{Courier New}         % 等宽字体：Adobe Courier Std

% we also define \song \kai for our habit
\setCJKfamilyfont{song}{SimSun} 
\newcommand*{\song}{\CJKfamily{song}}
\setCJKfamilyfont{kaiti}{KaiTi} 
\newcommand*{\kai}{\CJKfamily{kaiti}}
% define \li (隶书) \hei (黑体) \fs (仿宋)
\setCJKfamilyfont{lishu}{LiSu}
\newcommand*{\li}{\CJKfamily{lishu}}
\setCJKfamilyfont{heiti}[AutoFakeBold={3.17}]{SimHei} 
\newcommand*{\hei}{\CJKfamily{heiti}}
\setCJKfamilyfont{fs}[AutoFakeBold={3.17}]{FangSong} 
\newcommand*{\fs}{\CJKfamily{fs}}
```
主要是担心Adobe 宋体不符合模板，就想改成微软宋体了，学院对于这个居然没查吗，2333

**Comment by maxuewei2** [comment]
我也是因为担心思源宋体的粗体和微软宋体的粗体差别太大所以使用了假粗体方案，但我印象中当初用微软宋体假粗体会造成在PDF里有些字无法选中或者加粗有问题，所以最后用的Adobe宋体。但可能是我当时某些地方没配置好，你可以注意下有没有类似问题。

学院倒是没查这个，可能因为Adobe宋体和微软宋体看起来区别不大，所以不看PDF的字体数据大概没人会察觉？

**Comment by shiningliang** [comment]
23333 ，请问你说的假粗体是这个自定义的textBF命令吗
```
\newcommand{\textBF}[1]{%
    \special{pdf:literal direct 2 Tr 0.3 w}
     #1%
    \special{pdf:literal direct 0 Tr 0 w}
}
```
我正文都是用的常规的\textbf。。。

**Comment by maxuewei2** [comment]
我说的假粗体主要是指的在documentclass或者CJKfont里加AutoFakeBold选项。
那个textBF命令也是一种假粗体，只是没太用到。

**Comment by myweihp** [comment]
> 感谢回复，后来我看了下北大的模板，参考他们改了sty，在本地编译，目前字体配置是这样的
> 
> ```
> \setCJKmainfont[AutoFakeBold=true]{SimSun}   % 中文缺省字体: 宋体
> \setCJKsansfont{KaiTi}  % 中文无衬线字体：楷体
> \setCJKmonofont{SimSun}   % 中文数学字体：宋体
> \setmainfont{Times New Roman}    % 英文缺省字体：替代 Times New Roman
> \setsansfont{Arial}      % 英文无衬线字体: 替代 Arial
> \setmonofont{Courier New}         % 等宽字体：Adobe Courier Std
> 
> % we also define \song \kai for our habit
> \setCJKfamilyfont{song}{SimSun} 
> \newcommand*{\song}{\CJKfamily{song}}
> \setCJKfamilyfont{kaiti}{KaiTi} 
> \newcommand*{\kai}{\CJKfamily{kaiti}}
> % define \li (隶书) \hei (黑体) \fs (仿宋)
> \setCJKfamilyfont{lishu}{LiSu}
> \newcommand*{\li}{\CJKfamily{lishu}}
> \setCJKfamilyfont{heiti}[AutoFakeBold={3.17}]{SimHei} 
> \newcommand*{\hei}{\CJKfamily{heiti}}
> \setCJKfamilyfont{fs}[AutoFakeBold={3.17}]{FangSong} 
> \newcommand*{\fs}{\CJKfamily{fs}}
> ```
> 
> 主要是担心Adobe 宋体不符合模板，就想改成微软宋体了，学院对于这个居然没查吗，2333

你好，请问你最后提交的版本使用的是微软宋体吗？使用的粗体的方案是假粗体还是正常的粗体呢？有没有出现作者所说的微软宋体的假粗体的一些问题呢？

**Comment by shiningliang** [comment]
> 

我用的微软宋体，正常\textbf 就好了，没用假粗体方案，没注意到有问题

**Comment by myweihp** [comment]
> 

好的，我对比了一些字体设置理解为你没有用到作者提出的完整的假粗体方案（比如手动设定书脊之类），只是简单的指定了微软宋体并且AutoFakeBold=True，因此\textbf实际实现也是假粗体。我自己用微软宋体+{AutoFakeBold=True}+自动设定双语书脊看起来也没有什么问题，应该就确定这么使用了。谢谢！

**Comment by wuuu110** [comment]
原始版本有些字体无法编译，换了Adobe Song Std后好用了😃😃😃😃
